### ISSUE TITLE
Bug on settings page

### ISSUE THREAD

**Issue by local-minimum** [Scan-o-Matic/scanomatic#141]
Going into settings produces the following traceback:

```
scanomatic_1  | Traceback (most recent call last):
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
scanomatic_1  |     return self.wsgi_app(environ, start_response)
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
scanomatic_1  |     response = self.handle_exception(e)
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
scanomatic_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
scanomatic_1  |     reraise(exc_type, exc_value, tb)
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
scanomatic_1  |     response = self.full_dispatch_request()
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
scanomatic_1  |     rv = self.handle_user_exception(e)
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
scanomatic_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
scanomatic_1  |     reraise(exc_type, exc_value, tb)
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
scanomatic_1  |     rv = self.dispatch_request()
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
scanomatic_1  |     return self.view_functions[rule.endpoint](**req.view_args)
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/scanomatic/ui_server/ui_server.py", line 231, in _config
scanomatic_1  |     return render_template(Paths().ui_settings_template, **app_conf.model_copy())
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/scanomatic/io/app_config.py", line 234, in model_copy
scanomatic_1  |     return ApplicationSettingsFactory.copy(self._settings)
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/scanomatic/generics/abstract_model_factory.py", line 309, in copy
scanomatic_1  |     return cls.serializer.load_serialized_object(copy.deepcopy(cls.serializer.serialize(model)))[0]
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/scanomatic/generics/abstract_model_factory.py", line 975, in serialize
scanomatic_1  |     conf = self.serialize_into_conf(model, conf, self.get_section_name(model))
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/scanomatic/generics/abstract_model_factory.py", line 990, in serialize_into_conf
scanomatic_1  |     self._serialize_item(model, key, dtype, conf, section, factory)
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/scanomatic/generics/abstract_model_factory.py", line 1021, in _serialize_item
scanomatic_1  |     obj, conf, _SectionsLink.get_link(obj).section)
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/scanomatic/generics/abstract_model_factory.py", line 990, in serialize_into_conf
scanomatic_1  |     self._serialize_item(model, key, dtype, conf, section, factory)
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/scanomatic/generics/abstract_model_factory.py", line 997, in _serialize_item
scanomatic_1  |     obj = copy.deepcopy(model[key])
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/scanomatic/generics/model.py", line 57, in __getitem__
scanomatic_1  |     return getattr(self, item)
scanomatic_1  | AttributeError: 'UIServerModel' object has no attribute 'local'
```

The problem seems to be there lingers some `local` settings to the app:

```
scanomatic_1  |   File "/usr/local/lib/python2.7/site-packages/scanomatic/ui_server/ui_server.py", line 231, in _config
scanomatic_1  |     return render_template(Paths().ui_settings_template, **app_conf.model_copy())
```

They need to go.

__DoiD__: The settings page http://localhost:5000/settings is accessible again.

**Comment by local-minimum** [comment]
The fix needs to be pulled into the `scanomatic-scanning` repo as well.

**Comment by skymandr** [comment]
Is this still an issue?
